name    'counsyl-vagrant'
version '0.9.2'
source  'git://github.com/counsyl/puppet-vagrant.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing and configuring Vagrant'
description 'Puppet module for installing and configuring Vagrant'
project_page 'https://github.com/counsyl/puppet-vagrant'
